# Kings County Housing Dataset

## Using Keras to create a model of the data

In general to get a model to be very accurate, we would need data perhaps of photographs of the property, perhaps floor plans, and maybe even more historical data about each properties sale records. What other data sources can you think of that may improve our ability to predict the price of property?

In [6]:
#imports occuring as they are needed
import pandas as pd
pd.options.display.max_columns = None

#load the data as always with pandas
df = pd.read_csv('kc_house_data.csv')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

## fields

* date - Date house was sold
* price - Price is prediction target
* bedrooms - Number of Bedrooms/House
* bathrooms - Number of bathrooms/House
* sqft_living - Square footage of the home
* sqft_lot - square footage of the lot
* floors - Total floors (levels) in house
* waterfront - House which has a view to a waterfront
* view - Has been viewed
* condition - How good the condition is ( Overall )
* grade - overall grade given to the housing unit, based on King County grading system
* sqft_above - square footage of house apart from basement
* sqft_basement - square footage of the basement
* yr_built - Built Year
* yr_renovated - Year when house was renovated
* zipcode - zip
* lat - Latitude coordinate
* long - Longitude coordinate
* sqft_living15 - Living room area in 2015(implies-- some renovations) This might or might not have affected the lotsize area
* sqft_lot15 - lotSize area in 2015(implies-- some renovations)

In [7]:
df.dtypes

id                 int64
date              object
price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

In [8]:
#sample the date column to realise the date fomat
df['date'].sample(10)

19712    20141223T000000
14279    20140929T000000
4501     20150404T000000
16004    20140512T000000
5447     20140806T000000
20676    20140515T000000
19621    20141223T000000
3860     20150422T000000
13060    20150429T000000
12467    20140823T000000
Name: date, dtype: object

In [9]:
#split the date out into different properties
df["date"] = pd.to_datetime(df["date"])
df["date_year"] = df["date"].dt.year
df["date_month"] = df["date"].dt.month
df['date_quarter'] = df['date'].dt.quarter
df["date_day"] = df["date"].dt.day
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,date_year,date_month,date_quarter,date_day
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,2014,10,4,13
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,2014,12,4,9
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062,2015,2,1,25
3,2487200875,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,2014,12,4,9
4,1954400510,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,2015,2,1,18

In [10]:
#some columns are not useful (see field values)
df.drop(columns=['id', 'date', 'view', 'yr_renovated'], inplace=True)

In [11]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,condition,grade,sqft_above,sqft_basement,yr_built,zipcode,lat,long,sqft_living15,sqft_lot15,date_year,date_month,date_quarter,date_day
0,221900.0,3,1.00,1180,5650,1.0,0,3,7,1180,0,1955,98178,47.5112,-122.257,1340,5650,2014,10,4,13
1,538000.0,3,2.25,2570,7242,2.0,0,3,7,2170,400,1951,98125,47.7210,-122.319,1690,7639,2014,12,4,9
2,180000.0,2,1.00,770,10000,1.0,0,3,6,770,0,1933,98028,47.7379,-122.233,2720,8062,2015,2,1,25
3,604000.0,4,3.00,1960,5000,1.0,0,5,7,1050,910,1965,98136,47.5208,-122.393,1360,5000,2014,12,4,9
4,510000.0,3,2.00,1680,8080,1.0,0,3,8,1680,0,1987,98074,47.6168,-122.045,1800,7503,2015,2,1,18

In [12]:
X = df.drop(['price'], axis=1).values
Y = df['price'].values

In [13]:
from sklearn.model_selection import train_test_split

#split the data and scale training seperate to testing otherwise will leak test data into training data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

#create a seperation between training and val/testing
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X, Y, test_size=0.3)

#now we can scale

X_train = sc.fit_transform(X_train)
X_val_and_test = sc.transform (X_val_and_test)


#split the test and validation data 
# (validation is used after each epoch to test the accuracy of that epoch. Test is used after training)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)
print(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)

(15129, 20) (3242, 20) (3242, 20) (15129,) (3242,) (3242,)

## Linear regression 

To get a bench mark of the model

In [14]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [15]:
y_pred = regressor.predict(X_test)
print('Liner Regression R squared: %.4f' % regressor.score(X_test, Y_test))

Liner Regression R squared: 0.6875

In [16]:
import numpy as np
from sklearn.metrics import mean_squared_error
lin_mse = mean_squared_error(y_pred, Y_test)
lin_rmse = np.sqrt(lin_mse)
print('Liner Regression RMSE: %.4f' % lin_rmse)

Liner Regression RMSE: 200648.9752

In [17]:
from sklearn.metrics import mean_absolute_error

lin_mae = mean_absolute_error(y_pred, Y_test)
print('Liner Regression MAE: %.4f' % lin_mae)

Liner Regression MAE: 128794.2980

In [18]:
import keras

from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization, Activation #activation might be better split out
from keras.optimizers import Adam, RMSprop
from keras.callbacks import TensorBoard, EarlyStopping, ModelCheckpoint

from keras import metrics

from keras.utils import plot_model
from keras.models import load_model

from keras import optimizers
import time

Using TensorFlow backend.

## Notice

Note that the plot shows validation error as less than training error, which is quite deceptive. The reason for this is that training error is calculated for the entire epoch (and at its begining it was much worse than at the end), whereas the validation error is taken from the last batch (after the model improved).

In [99]:
#set the learning rate
lr = 0.3
opt = optimizers.Adam(lr=lr)

#all tanh fail

In [100]:
now = time.strftime("run_%c") #record the current time

#network callbacks.
tensorboard = TensorBoard(log_dir='./tensorboards/'+now + "_" + str(lr), histogram_freq=0, write_graph=True)
#earlyStopping = EarlyStopping(monitor='val_mean_absolute_error', patience=20, verbose=1)
checkpointSave = ModelCheckpoint(filepath='./best_model_'+now+'.h5', monitor='val_mean_absolute_error', save_best_only=True)

n_cols = X_train.shape[1]

#NOTE: Simpler models may work and improve on the linear regression, but 2/3 rule is just a rule of thumb and
#I have improved models not using this rule
#It makes sense as there are large gaps in the data (we don't have data for every possible type of property)
t_model = Sequential()

#1 exerise - remove layers
#2 exercise, change number of neurons in layers
#3 exercise change/remove the drop out layers and see affect of over fitting
#4 exercise change the learning rate

t_model.add(Dense(12, activation="relu", kernel_initializer='normal', input_shape=(n_cols,)))
#t_model.add(Dropout(0.2)) #exercise, get the room to define different drop outs perhaps?

t_model.add(Dense(4, activation="relu", kernel_initializer='normal')) 
#t_model.add(Dropout(0.1))

#t_model.add(Dense(12, activation="relu", kernel_initializer='normal'))
#t_model.add(Dropout(0.1))

t_model.add(Dense(4, activation="relu", kernel_initializer='normal'))
#t_model.add(Dropout(0.1))

t_model.add(Dense(12, activation="relu", kernel_initializer='normal'))

t_model.add(Dense(1))

t_model.compile(
    loss='mean_squared_error',
    optimizer=opt,
    metrics=[metrics.mae])
t_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_159 (Dense)            (None, 12)                252
_________________________________________________________________
dense_160 (Dense)            (None, 4)                 52
_________________________________________________________________
dense_161 (Dense)            (None, 4)                 20
_________________________________________________________________
dense_162 (Dense)            (None, 12)                60
_________________________________________________________________
dense_163 (Dense)            (None, 1)                 13
=================================================================
Total params: 397
Trainable params: 397
Non-trainable params: 0
_________________________________________________________________

In [101]:
t_model.fit(X_train, Y_train,
    batch_size=25,
    epochs=100,
    verbose=1, # Change it to 2, if wished to observe execution
    validation_data=(X_val, Y_val),
    callbacks=[tensorboard, #earlyStopping
              ])

Train on 15129 samples, validate on 3242 samples
Epoch 1/100
15129/15129 [==============================] - 4s 280us/step - loss: 60294105383.1386 - mean_absolute_error: 156868.9373 - val_loss: 49332997859.0993 - val_mean_absolute_error: 146471.5501
Epoch 2/100
15129/15129 [==============================] - 4s 257us/step - loss: 42363359311.1910 - mean_absolute_error: 130136.9360 - val_loss: 31749402285.5620 - val_mean_absolute_error: 117300.8273
Epoch 3/100
15129/15129 [==============================] - 4s 241us/step - loss: 39570448843.9844 - mean_absolute_error: 125718.0995 - val_loss: 30391738354.1024 - val_mean_absolute_error: 111409.4669
Epoch 4/100
15129/15129 [==============================] - 4s 237us/step - loss: 38632651115.9231 - mean_absolute_error: 121991.2899 - val_loss: 31751005821.2363 - val_mean_absolute_error: 112529.8812
Epoch 5/100
15129/15129 [==============================] - 4s 239us/step - loss: 33215160864.9285 - mean_absolute_error: 115916.7279 - val_loss: 29072825957.5472 - val_mean_absolute_error: 107008.5886
Epoch 6/100
15129/15129 [==============================] - 4s 244us/step - loss: 34485864762.1918 - mean_absolute_error: 117114.8539 - val_loss: 30574904955.3411 - val_mean_absolute_error: 111524.6570
Epoch 7/100
15129/15129 [==============================] - 4s 248us/step - loss: 32680446474.1358 - mean_absolute_error: 112069.7824 - val_loss: 35095590887.5213 - val_mean_absolute_error: 116968.9462
Epoch 8/100
15129/15129 [==============================] - 4s 243us/step - loss: 29201955547.9580 - mean_absolute_error: 107318.6907 - val_loss: 29340552411.2030 - val_mean_absolute_error: 106007.8788
Epoch 9/100
15129/15129 [==============================] - 4s 241us/step - loss: 28511938698.7703 - mean_absolute_error: 106555.0382 - val_loss: 39254613496.1036 - val_mean_absolute_error: 123193.2793
Epoch 10/100
15129/15129 [==============================] - 4s 247us/step - loss: 27723349162.8020 - mean_absolute_error: 103700.6730 - val_loss: 28796302793.0413 - val_mean_absolute_error: 109767.2774
Epoch 11/100
15129/15129 [==============================] - 4s 246us/step - loss: 28109163933.1297 - mean_absolute_error: 104351.4942 - val_loss: 22706088696.6564 - val_mean_absolute_error: 90745.0341
Epoch 12/100
15129/15129 [==============================] - 4s 283us/step - loss: 25883114119.2846 - mean_absolute_error: 100349.2581 - val_loss: 24267367162.1567 - val_mean_absolute_error: 99919.0407
Epoch 13/100
15129/15129 [==============================] - 4s 253us/step - loss: 25548497816.6964 - mean_absolute_error: 100591.8034 - val_loss: 25690572651.5484 - val_mean_absolute_error: 99022.1608
Epoch 14/100
15129/15129 [==============================] - 4s 275us/step - loss: 25936300426.0258 - mean_absolute_error: 100051.9595 - val_loss: 38521987616.2171 - val_mean_absolute_error: 135267.0269
Epoch 15/100
15129/15129 [==============================] - 4s 254us/step - loss: 25498247948.4878 - mean_absolute_error: 99713.1858 - val_loss: 27523354831.4374 - val_mean_absolute_error: 104851.1377
Epoch 16/100
15129/15129 [==============================] - 5s 314us/step - loss: 28534469257.3320 - mean_absolute_error: 105634.2947 - val_loss: 21465734930.3196 - val_mean_absolute_error: 88195.7021
Epoch 17/100
15129/15129 [==============================] - 4s 243us/step - loss: 23957714805.5343 - mean_absolute_error: 96887.3106 - val_loss: 20444013443.9482 - val_mean_absolute_error: 88286.3071
Epoch 18/100
15129/15129 [==============================] - 4s 246us/step - loss: 24732578401.7281 - mean_absolute_error: 99015.7768 - val_loss: 27572707707.4991 - val_mean_absolute_error: 111592.7738
Epoch 19/100
15129/15129 [==============================] - 4s 256us/step - loss: 25749202413.2091 - mean_absolute_error: 99722.5459 - val_loss: 20705037259.7261 - val_mean_absolute_error: 89377.6792
Epoch 20/100
15129/15129 [==============================] - 4s 243us/step - loss: 24816854232.0661 - mean_absolute_error: 99769.5776 - val_loss: 19707057237.1228 - val_mean_absolute_error: 91390.1062
Epoch 21/100
15129/15129 [==============================] - 4s 244us/step - loss: 25841840450.2801 - mean_absolute_error: 100197.2061 - val_loss: 24086330852.3627 - val_mean_absolute_error: 100603.9271
Epoch 22/100
15129/15129 [==============================] - 4s 244us/step - loss: 25533773492.7347 - mean_absolute_error: 97941.2564 - val_loss: 21174402671.4966 - val_mean_absolute_error: 90983.8395
Epoch 23/100
15129/15129 [==============================] - 4s 243us/step - loss: 23831269288.9746 - mean_absolute_error: 97243.5891 - val_loss: 19316167505.2535 - val_mean_absolute_error: 86210.3450
Epoch 24/100
15129/15129 [==============================] - 4s 243us/step - loss: 25710005965.3889 - mean_absolute_error: 102158.4204 - val_loss: 24499660752.6218 - val_mean_absolute_error: 98641.9655
Epoch 25/100
15129/15129 [==============================] - 4s 244us/step - loss: 24582055634.7021 - mean_absolute_error: 99193.9153 - val_loss: 33973436468.2739 - val_mean_absolute_error: 115901.7929
Epoch 26/100
15129/15129 [==============================] - 4s 244us/step - loss: 24113841651.6645 - mean_absolute_error: 95716.8418 - val_loss: 22824052705.3621 - val_mean_absolute_error: 93745.5342
Epoch 27/100
15129/15129 [==============================] - 4s 244us/step - loss: 23058613653.5152 - mean_absolute_error: 97574.8260 - val_loss: 20646512411.4793 - val_mean_absolute_error: 100220.0767
Epoch 28/100
15129/15129 [==============================] - 4s 247us/step - loss: 23856013603.1283 - mean_absolute_error: 97846.4620 - val_loss: 28031044210.3393 - val_mean_absolute_error: 102324.8738
Epoch 29/100
15129/15129 [==============================] - 4s 253us/step - loss: 23272854506.4086 - mean_absolute_error: 96620.9293 - val_loss: 24077874188.3183 - val_mean_absolute_error: 96734.6392
Epoch 30/100
15129/15129 [==============================] - 4s 245us/step - loss: 23836732045.9346 - mean_absolute_error: 97770.0822 - val_loss: 29958654662.6724 - val_mean_absolute_error: 110467.0602
Epoch 31/100
15129/15129 [==============================] - 4s 247us/step - loss: 26240231704.0111 - mean_absolute_error: 102715.9940 - val_loss: 21219912793.7027 - val_mean_absolute_error: 90717.4527
Epoch 32/100
15129/15129 [==============================] - 4s 245us/step - loss: 21752834917.2730 - mean_absolute_error: 94103.6730 - val_loss: 68148971676.6638 - val_mean_absolute_error: 184601.7859
Epoch 33/100
15129/15129 [==============================] - 4s 252us/step - loss: 23737084474.6910 - mean_absolute_error: 97275.0531 - val_loss: 20359909776.3455 - val_mean_absolute_error: 88257.6999
Epoch 34/100
15129/15129 [==============================] - 4s 260us/step - loss: 24999997610.2436 - mean_absolute_error: 99116.2351 - val_loss: 19508366705.8655 - val_mean_absolute_error: 85728.6556
Epoch 35/100
15129/15129 [==============================] - 4s 243us/step - loss: 25955794143.2576 - mean_absolute_error: 101060.3262 - val_loss: 20376406787.6323 - val_mean_absolute_error: 90935.0372
Epoch 36/100
15129/15129 [==============================] - 4s 243us/step - loss: 22225813955.9299 - mean_absolute_error: 95371.3313 - val_loss: 56379800723.8199 - val_mean_absolute_error: 184553.7097
Epoch 37/100
15129/15129 [==============================] - 4s 247us/step - loss: 23775518490.5154 - mean_absolute_error: 98032.1038 - val_loss: 23159610344.6268 - val_mean_absolute_error: 96388.7100
Epoch 38/100
15129/15129 [==============================] - 4s 250us/step - loss: 22279763389.6691 - mean_absolute_error: 94573.1651 - val_loss: 19641598359.7680 - val_mean_absolute_error: 87196.0240
Epoch 39/100
15129/15129 [==============================] - 4s 247us/step - loss: 22528339929.8597 - mean_absolute_error: 95321.2054 - val_loss: 20784768929.7175 - val_mean_absolute_error: 87953.3761
Epoch 40/100
15129/15129 [==============================] - 4s 242us/step - loss: 21006321176.6372 - mean_absolute_error: 92616.1518 - val_loss: 18283677473.0858 - val_mean_absolute_error: 84269.8308
Epoch 41/100

15129/15129 [==============================] - 4s 236us/step - loss: 21290594791.0244 - mean_absolute_error: 93565.5368 - val_loss: 27216377320.7847 - val_mean_absolute_error: 95273.1026
Epoch 42/100
15129/15129 [==============================] - 4s 241us/step - loss: 20886983877.0637 - mean_absolute_error: 91979.0207 - val_loss: 27794843446.2480 - val_mean_absolute_error: 109377.1076
Epoch 43/100
15129/15129 [==============================] - 4s 234us/step - loss: 24878753745.5176 - mean_absolute_error: 97680.6654 - val_loss: 25711775769.4263 - val_mean_absolute_error: 109747.9529
Epoch 44/100
15129/15129 [==============================] - 4s 237us/step - loss: 22811797273.0941 - mean_absolute_error: 96525.8017 - val_loss: 52025974342.1197 - val_mean_absolute_error: 148753.4302
Epoch 45/100
15129/15129 [==============================] - 4s 234us/step - loss: 21234180331.3393 - mean_absolute_error: 92822.2563 - val_loss: 17803570294.7613 - val_mean_absolute_error: 81466.7492
Epoch 46/100
15129/15129 [==============================] - 4s 241us/step - loss: 20727472845.7019 - mean_absolute_error: 92135.5796 - val_loss: 23326908511.2301 - val_mean_absolute_error: 104394.9467
Epoch 47/100
15129/15129 [==============================] - 4s 236us/step - loss: 21572991971.6402 - mean_absolute_error: 93585.4316 - val_loss: 18026658046.1838 - val_mean_absolute_error: 88256.1896
Epoch 48/100
15129/15129 [==============================] - 4s 238us/step - loss: 22971302336.4103 - mean_absolute_error: 97683.9359 - val_loss: 22198303346.6552 - val_mean_absolute_error: 99827.1852
Epoch 49/100
15129/15129 [==============================] - 4s 234us/step - loss: 22362381681.2532 - mean_absolute_error: 94610.0408 - val_loss: 21584175751.7384 - val_mean_absolute_error: 90734.9893
Epoch 50/100
15129/15129 [==============================] - 4s 240us/step - loss: 21296341938.5012 - mean_absolute_error: 93646.6670 - val_loss: 22552974757.3498 - val_mean_absolute_error: 103529.2406
Epoch 51/100
15129/15129 [==============================] - 4s 232us/step - loss: 21490965088.2390 - mean_absolute_error: 93254.2956 - val_loss: 21716591525.5867 - val_mean_absolute_error: 90643.4434
Epoch 52/100
15129/15129 [==============================] - 4s 232us/step - loss: 21780436597.5173 - mean_absolute_error: 93493.0459 - val_loss: 19408506119.0278 - val_mean_absolute_error: 87591.3045
Epoch 53/100
15129/15129 [==============================] - 4s 235us/step - loss: 22465545453.6744 - mean_absolute_error: 95217.0219 - val_loss: 23249303958.0308 - val_mean_absolute_error: 103315.4783
Epoch 54/100
15129/15129 [==============================] - 4s 233us/step - loss: 20838403183.2565 - mean_absolute_error: 93773.3856 - val_loss: 22099004695.9260 - val_mean_absolute_error: 91974.2452
Epoch 55/100
15129/15129 [==============================] - 4s 234us/step - loss: 20956408603.1923 - mean_absolute_error: 91410.3235 - val_loss: 23364303080.9426 - val_mean_absolute_error: 107574.6741
Epoch 56/100
15129/15129 [==============================] - 4s 234us/step - loss: 21307616349.3032 - mean_absolute_error: 93384.5312 - val_loss: 19264740267.2721 - val_mean_absolute_error: 91287.4742
Epoch 57/100
15129/15129 [==============================] - 4s 233us/step - loss: 22241162213.0531 - mean_absolute_error: 96258.1331 - val_loss: 45475350629.7051 - val_mean_absolute_error: 167862.9291
Epoch 58/100
15129/15129 [==============================] - 4s 235us/step - loss: 22722200314.5514 - mean_absolute_error: 94437.4618 - val_loss: 190031213658.3344 - val_mean_absolute_error: 366591.6985
Epoch 59/100
15129/15129 [==============================] - 4s 233us/step - loss: 23792972096.1988 - mean_absolute_error: 97265.1118 - val_loss: 24119749063.4621 - val_mean_absolute_error: 105197.9330
Epoch 60/100
15129/15129 [==============================] - 4s 239us/step - loss: 21759863740.0954 - mean_absolute_error: 94464.5682 - val_loss: 21254805729.8359 - val_mean_absolute_error: 86900.5084
Epoch 61/100
15129/15129 [==============================] - 4s 240us/step - loss: 23264245838.4972 - mean_absolute_error: 98737.4742 - val_loss: 27159947952.4047 - val_mean_absolute_error: 119644.0865
Epoch 62/100
15129/15129 [==============================] - 4s 250us/step - loss: 21715509981.7854 - mean_absolute_error: 92408.3540 - val_loss: 18177540254.4799 - val_mean_absolute_error: 88962.1000
Epoch 63/100
15129/15129 [==============================] - 4s 235us/step - loss: 22400093974.1836 - mean_absolute_error: 94328.9492 - val_loss: 19536078014.4602 - val_mean_absolute_error: 90680.5637
Epoch 64/100
15129/15129 [==============================] - 4s 237us/step - loss: 20444714707.9712 - mean_absolute_error: 92055.3378 - val_loss: 20506404041.9889 - val_mean_absolute_error: 86930.6091
Epoch 65/100
15129/15129 [==============================] - 4s 234us/step - loss: 20912073693.7178 - mean_absolute_error: 92829.1235 - val_loss: 18318553137.5102 - val_mean_absolute_error: 86490.9989
Epoch 66/100
15129/15129 [==============================] - 4s 233us/step - loss: 20616503969.1231 - mean_absolute_error: 92496.5862 - val_loss: 19365569699.8495 - val_mean_absolute_error: 85745.7263
Epoch 67/100
15129/15129 [==============================] - 4s 237us/step - loss: 22839969397.5004 - mean_absolute_error: 96605.8384 - val_loss: 18284001489.0167 - val_mean_absolute_error: 82418.0474
Epoch 68/100
15129/15129 [==============================] - 4s 238us/step - loss: 23999063041.3706 - mean_absolute_error: 98748.4451 - val_loss: 19299717526.8994 - val_mean_absolute_error: 87088.0533
Epoch 69/100
15129/15129 [==============================] - 4s 234us/step - loss: 21735524589.1837 - mean_absolute_error: 92176.5719 - val_loss: 18797812096.6317 - val_mean_absolute_error: 84475.4090
Epoch 70/100
15129/15129 [==============================] - 4s 236us/step - loss: 19295460791.5944 - mean_absolute_error: 89076.7999 - val_loss: 19808276701.0191 - val_mean_absolute_error: 90444.5682
Epoch 71/100
15129/15129 [==============================] - 4s 233us/step - loss: 21010752676.1859 - mean_absolute_error: 92486.1868 - val_loss: 19623407265.6385 - val_mean_absolute_error: 86880.8480
Epoch 72/100
15129/15129 [==============================] - 4s 239us/step - loss: 21549930348.5491 - mean_absolute_error: 91766.9534 - val_loss: 18116501507.9482 - val_mean_absolute_error: 86592.7963
Epoch 73/100
15129/15129 [==============================] - 4s 232us/step - loss: 21644614304.5647 - mean_absolute_error: 95628.6980 - val_loss: 25682238356.4516 - val_mean_absolute_error: 95720.7413
Epoch 74/100
15129/15129 [==============================] - 4s 233us/step - loss: 21356335031.0191 - mean_absolute_error: 94079.3469 - val_loss: 33555632913.8458 - val_mean_absolute_error: 125160.4614
Epoch 75/100
15129/15129 [==============================] - 4s 234us/step - loss: 23167212804.1457 - mean_absolute_error: 97991.0935 - val_loss: 29941432015.2005 - val_mean_absolute_error: 118489.0790
Epoch 76/100
15129/15129 [==============================] - 4s 235us/step - loss: 23414631930.0184 - mean_absolute_error: 95101.8745 - val_loss: 18415812588.8118 - val_mean_absolute_error: 83240.8570
Epoch 77/100
15129/15129 [==============================] - 4s 235us/step - loss: 19363286872.6330 - mean_absolute_error: 88795.5856 - val_loss: 21465831913.1795 - val_mean_absolute_error: 89439.1122
Epoch 78/100
15129/15129 [==============================] - 4s 236us/step - loss: 22758755970.0390 - mean_absolute_error: 96010.6016 - val_loss: 23040050160.9969 - val_mean_absolute_error: 101956.8381
Epoch 79/100
15129/15129 [==============================] - 4s 235us/step - loss: 22704113306.0839 - mean_absolute_error: 96576.1056 - val_loss: 18553781924.4812 - val_mean_absolute_error: 86623.7334
Epoch 80/100
15129/15129 [==============================] - 4s 234us/step - loss: 20899843053.1160 - mean_absolute_error: 92342.4438 - val_loss: 19801181127.7779 - val_mean_absolute_error: 86362.8455
Epoch 81/100
15129/15129 [==============================] - 4s 237us/step - loss: 22198387704.9608 - mean_absolute_error: 97162.6573 - val_loss: 18640094414.5688 - val_mean_absolute_error: 91125.1031

Epoch 82/100
15129/15129 [==============================] - 4s 233us/step - loss: 20078280532.4873 - mean_absolute_error: 91223.5659 - val_loss: 17989227923.1092 - val_mean_absolute_error: 87202.5971
Epoch 83/100
15129/15129 [==============================] - 3s 231us/step - loss: 24655385994.8718 - mean_absolute_error: 100498.4054 - val_loss: 23270863931.8544 - val_mean_absolute_error: 113099.2150
Epoch 84/100
15129/15129 [==============================] - 3s 231us/step - loss: 20672291619.7544 - mean_absolute_error: 92973.5576 - val_loss: 24056887444.6095 - val_mean_absolute_error: 96195.4828
Epoch 85/100
15129/15129 [==============================] - 3s 231us/step - loss: 20619978451.1928 - mean_absolute_error: 90504.1202 - val_loss: 21846612034.8032 - val_mean_absolute_error: 96155.1078
Epoch 86/100
15129/15129 [==============================] - 3s 230us/step - loss: 20794530241.9332 - mean_absolute_error: 93754.5283 - val_loss: 17143590295.2153 - val_mean_absolute_error: 81984.1047
Epoch 87/100
15129/15129 [==============================] - 4s 232us/step - loss: 22561749056.7911 - mean_absolute_error: 96130.0364 - val_loss: 18710691634.7736 - val_mean_absolute_error: 84303.6107
Epoch 88/100
15129/15129 [==============================] - 3s 231us/step - loss: 22013607796.5528 - mean_absolute_error: 94115.3068 - val_loss: 17152897386.2060 - val_mean_absolute_error: 82153.8838
Epoch 89/100
15129/15129 [==============================] - 4s 267us/step - loss: 18734500478.7732 - mean_absolute_error: 88144.6837 - val_loss: 17056740123.4793 - val_mean_absolute_error: 81191.7984
Epoch 90/100
15129/15129 [==============================] - 4s 244us/step - loss: 18549857097.8777 - mean_absolute_error: 88229.8834 - val_loss: 23377397328.3849 - val_mean_absolute_error: 98504.6026
Epoch 91/100
15129/15129 [==============================] - 3s 231us/step - loss: 22780236072.6277 - mean_absolute_error: 96291.0535 - val_loss: 27068070568.0345 - val_mean_absolute_error: 105489.6449
Epoch 92/100
15129/15129 [==============================] - 3s 229us/step - loss: 19678647541.3904 - mean_absolute_error: 90156.5332 - val_loss: 19231121998.0950 - val_mean_absolute_error: 85238.1090
Epoch 93/100
15129/15129 [==============================] - 4s 234us/step - loss: 19018658542.9943 - mean_absolute_error: 89541.8285 - val_loss: 19228057751.0574 - val_mean_absolute_error: 86663.2432
Epoch 94/100
15129/15129 [==============================] - 3s 230us/step - loss: 19840355468.9701 - mean_absolute_error: 91432.6539 - val_loss: 25641137976.8538 - val_mean_absolute_error: 106509.9627
Epoch 95/100
15129/15129 [==============================] - 4s 233us/step - loss: 20655940014.2539 - mean_absolute_error: 92020.6504 - val_loss: 25644064551.6397 - val_mean_absolute_error: 109018.8574
Epoch 96/100
15129/15129 [==============================] - 4s 239us/step - loss: 18017914247.7753 - mean_absolute_error: 87106.8356 - val_loss: 18796855424.6317 - val_mean_absolute_error: 86512.6361
Epoch 97/100
15129/15129 [==============================] - 4s 236us/step - loss: 23331077862.4491 - mean_absolute_error: 95530.8723 - val_loss: 36740408914.7539 - val_mean_absolute_error: 140115.2708
Epoch 98/100
15129/15129 [==============================] - 4s 239us/step - loss: 23679228378.2997 - mean_absolute_error: 97452.0988 - val_loss: 18386895469.2067 - val_mean_absolute_error: 84162.2538
Epoch 99/100
15129/15129 [==============================] - 4s 281us/step - loss: 19959195588.6237 - mean_absolute_error: 91023.2080 - val_loss: 20591433128.9031 - val_mean_absolute_error: 92313.2332
Epoch 100/100
15129/15129 [==============================] - 4s 251us/step - loss: 19079814731.2483 - mean_absolute_error: 89403.6172 - val_loss: 19564336691.2474 - val_mean_absolute_error: 89694.9505

In [ ]:
tensorboard

In [85]:
train_score = t_model.evaluate(X_train, Y_train, verbose=0)
valid_score = t_model.evaluate(X_val, Y_val, verbose=0)
test_score = t_model.evaluate(X_test, Y_test, verbose=0)

print(train_score)
print(valid_score)
print(test_score)
print('Train MAE: ', round(train_score[1], 4), ', Train Loss: ', round(train_score[0], 4)) 
print('Val MAE: ', round(valid_score[1], 4), ', Val Loss: ', round(valid_score[0], 4))
print('Test MAE: ', round(test_score[1], 4), ', Test Loss: ', round(test_score[0], 4))

[139895116821.0499, 231751.6209514839]
[117636728967.18568, 230717.96310148056]
[128859685020.66379, 229010.96377621838]
Train MAE:  231751.621 , Train Loss:  139895116821.0499
Val MAE:  230717.9631 , Val Loss:  117636728967.1857
Test MAE:  229010.9638 , Test Loss:  128859685020.6638

# things for them to learn 

* different activation functions
* explanation of how the activation function can model a non linear function
* https://missinglink.ai/guides/neural-network-concepts/7-types-neural-network-activation-functions-right/
* https://towardsdatascience.com/activation-functions-neural-networks-1cbd9f8d91d6
* understand dropout, and regularization as techniques
* understand that more complex models are used for image recognition
* look at a model for image recognition
* understand what a convolution is
* understand there are a lot of tools and techniques to the NN and will take time resource and learning to experience
* need to watch the string of videos


## exercise

* add in drop out (different values for each network)
* and in regularization to second layer

* https://ml4a.github.io/ml4a/neural_networks/